#!/bin/bash
#
# Change the PDF title.

function guide() {
    echo -e "usage:  `basename $0` \"PDF Title\" \"Author Name\" pdfFileName.pdf";
    exit 1;
}


if [ "$#" -lt 3 ]; then
    guide;
fi


exiftool -Title="$1" -Author="$2" $3
